name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Runs at 01:00 UTC on Thu.
    - cron: '0 1 * * THU'

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build the Docker image
        run: >-
          echo ".git" > .dockerignore
          
          docker buildx build . --file Dockerfile --compress --no-cache --rm --force-rm --push
          --platform linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
          --build-arg VCS_REF=`git rev-parse --short HEAD`
          --build-arg VCS_URL=`git remote get-url origin`
          --build-arg VERSION="1.0"
          --build-arg TIMEZONE="Asia/Dhaka"
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/vapoursynth-av1an:$(date +%Y.%j.%H)
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/vapoursynth-av1an:latest
          
          docker buildx imagetools inspect ${{ secrets.DOCKERHUB_USERNAME }}/vapoursynth-av1an:latest
